### ISSUE TITLE
exec /entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by dillfrescott** [diademiemi/container-images#1]
This is the error it gives me when attempting to run the dropspace docker container :(

**Comment by diademiemi** [comment]
My bad! I seem to have forgotten to push my changes where it did work..

**Comment by diademiemi** [comment]
Should be fixed with https://github.com/diademiemi/container-images/commit/a038e9b96f35bd80826226297cadaad7e62126e3 after CI builds and uploads the new container image

**Comment by dillfrescott** [comment]
Okay! Awesome! Thank you so much!~
